name: Test website generation

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "tests/**"
      - "examples/**"
      - "**.json"
      - "**.csv"
      - "**.html"

env:
  FORCE_COLOR: 1 # Request colored output from CLI tools supporting it
  CLICOLOR_FORCE: 1 # recognized by uv

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  test-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "0.11.26"
          python-version: "3.14"
      - run: uv sync --group=dev
      - run: uv pip freeze
      - name: Regenerate examples and docs
        run: uv run python scripts/regenerate.py --download-typeshed
      - name: Check the generated files with prek
        run: uv run prek run --all-files
      - name: Build docs
        run: uv run mkdocs build --strict
      - name: Upload docs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: doc-html
          path: site
